
INSERT INTO GLOBAL_MESSAGES (MESSAGE_TYPE,SENDER,CONTENT) VALUES ('CHAT','BANR','Welcome to the global chat');
INSERT INTO PRIVATE_MESSAGES (SENDER,RECEIVER,CONTENT) VALUES ('TEST','TEST','TEST');

INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('gonzalo','admin','ROLE_ADMIN');
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('alejandro','admin','ROLE_ADMIN');
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('maria','admin','ROLE_ADMIN');
