
INSERT INTO GLOBAL_MESSAGES (MESSAGE_TYPE,SENDER,CONTENT) VALUES ('CHAT','BASED_INDIVIDUAL','Birds are not real');
INSERT INTO GLOBAL_MESSAGES (MESSAGE_TYPE,SENDER,CONTENT) VALUES ('CHAT','MEGA_CHAD69','I agree');
INSERT INTO PRIVATE_MESSAGES (SENDER,RECEIVER,CONTENT) VALUES ('TEST','TEST','TEST');


INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('gonzalo','admin','ROLE_ADMIN');
INSERT INTO USER (USERNAME,PASSWORD,ROLE) VALUES ('alejandro','admin','ROLE_ADMIN');
