
DROP TABLE IF EXISTS GLOBAL_MESSAGES;
DROP TABLE IF EXISTS PRIVATE_MESSAGES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE GLOBAL_MESSAGES (
    GLOBAL_MESSAGE_ID INTEGER SERIAL PRIMARY KEY,
    MESSAGE_TYPE VARCHAR(255) NOT NULL,
    SENDER VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL
);

CREATE TABLE PRIVATE_MESSAGES (
    PRIVATE_MESSAGE_ID INTEGER SERIAL PRIMARY KEY,
    SENDER VARCHAR(255) NOT NULL,
    RECEIVER VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL
);

CREATE TABLE `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `ROLE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE PUBLIC_USERS(
    USERNAME VARCHAR(50) NOT NULL PRIMARY KEY
);