
DROP TABLE IF EXISTS MESSAGES;

CREATE TABLE MESSAGES (
    MESSAGE_ID INTEGER SERIAL PRIMARY KEY,
    SENDER VARCHAR(255) NOT NULL,
    RECEIVER VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL
);