
DROP TABLE IF EXISTS GLOBAL_MESSAGES;
DROP TABLE IF EXISTS PRIVATE_MESSAGES;

CREATE TABLE GLOBAL_MESSAGES (
    GLOBAL_MESSAGE_ID INTEGER SERIAL PRIMARY KEY,
    MESSAGE_TYPE VARCHAR(255) NOT NULL,
    SENDER VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL
);

CREATE TABLE PRIVATE_MESSAGES (
    PRIVATE_MESSAGE_ID INTEGER SERIAL PRIMARY KEY,
    SENDER VARCHAR(255) NOT NULL,
    RECEIVER VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL
);