
INSERT INTO GLOBAL_MESSAGES (MESSAGE_TYPE,SENDER,CONTENT) VALUES ('CHAT','BASED_INDIVIDUAL','Birds are not real');
INSERT INTO PRIVATE_MESSAGES (SENDER,RECEIVER,CONTENT) VALUES ('TEST','TEST','TEST');